name: SMA Energy Meter (developer version)
slug: sma-em-dev
description: Add-on for the SMA Energy meter
version: 2025.1.13c
startup: services
init: false
boot: auto
url: 'https://github.com/kellerza/hassio-sma-em-dev'
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
ports: {}
ports_description: {}
host_network: true
options:
    MCASTGRP: 239.12.255.254
    MQTT_HOST: core-mosquitto
    MQTT_PORT: 1883
    MQTT_USERNAME: hass
    MQTT_PASSWORD: my_very_secure_password
    IPBIND: "0.0.0.0"
    SMA_SERIALS: []
    FIELDS:
        - p1consume
        - 'p1consumecounter:max'
        - u1
    THRESHOLD: 80
    RECONNECT_INTERVAL: 86400
    DEBUG: 0
schema:
    MCASTGRP: str?
    MQTT_HOST: str
    MQTT_PORT: port
    MQTT_USERNAME: str
    MQTT_PASSWORD: password
    IPBIND: str
    SMA_SERIALS:
        - str
    FIELDS:
        - str
    THRESHOLD: 'int(10,1000)'
    RECONNECT_INTERVAL: 'int(60,86400)'
    DEBUG: bool
